name: Crypto Data Fetcher

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests gspread google-auth

      - name: Create service account file
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          python -c "import os; open('service-account.json','w').write(os.environ['GOOGLE_SERVICE_ACCOUNT_JSON'])"

      - name: Run crypto fetcher
        run: |
          python src/fetcher.py

      - name: Update GitHub CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/crypto_data.csv

          git diff --cached --quiet || git commit -m "Update crypto data"

          git push
